### PR TITLE
ping: also bind the ICMP socket to the specific device

### LINKED ISSUE #55: [PATCH] broken "-I <ifname>" option
In Debian/testing, "ping -I..." from package 3:20150815-2 is not working.
Following patch fixes it:

--- iputils-master/ping.c.orig  2016-04-05 19:44:37.000000000 +0300
+++ iputils-master/ping.c       2016-04-15 18:00:08.000000000 +0300
@@ -570,7 +570,7 @@
                        strncpy(ifr.ifr_name, device, IFNAMSIZ-1);

                        enable_capability_raw();
-                       rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
+                       rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
                        disable_capability_raw();

                        if (rc == -1) {

### PR DESCRIPTION
**Pull request by lilydjwg**
Or the default route is used. Not binding the probe_fd to the same device will result wrong source address being selected (I get a warning for this).

I've only tested for IPv4 because I don't have access to IPv6.

This closes #55.

### CODE REVIEW

File: ping.c [hunk 1]
```diff
@@ -570,6 +570,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
 
 			enable_capability_raw();
 			rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
+			rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
```
Comment (jsynacek) [inline ping.c]: You lose the first return code here.

**Comment by lilydjwg** [comment]
@jsynacek I've updated the code.

**Comment by okias** [comment]
can you also test this code on multipath enabled kernel? https://www.multipath-tcp.org/

**Comment by pavlix** [comment]
I would personally prefer if the resulting code looked similar for both protocols. While the IPv6 code looks pretty simple, the IPv4 version looks unnecessarily complicated even though it is supposed to do the same thing.

**Comment by pavlix** [comment]
I changed my mind. I'm not going to change the structure of the code right now. On the other hand I don't care much about multipath TCP as long as the feature doesn't work at all. Also there is no mtcp code in IPv6 unless I missed something. I personally would merge the pull request as is.

File: ping.c [hunk 2]
```diff
@@ -563,31 +563,36 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
...
-					struct ip_mreqn imr;
-					if (ioctl(probe_fd, SIOCGIFINDEX, &ifr) < 0) {
-						fprintf(stderr, "ping: unknown iface %s\n", device);
-						exit(2);
-					}
-					memset(&imr, 0, sizeof(imr));
-					imr.imr_ifindex = ifr.ifr_ifindex;
-					if (setsockopt(probe_fd, SOL_IP, IP_MULTICAST_IF, &imr, sizeof(imr)) == -1) {
-						perror("ping: IP_MULTICAST_IF");
+			for(i=0; i<2; i++){
```
Comment (okias) [inline ping.c]: coding style, spaces, improve please.

**Comment by n3ph** [comment]
Patch is working as expected and fixes #55. Please add this to the [iputils-20160919 release](https://github.com/iputils/iputils/milestone/1)
